baseURL = 'https://hugo-blog-three-xi.vercel.app/'
languageCode = 'zh-cn'
title = 'Bob的博客'
theme = 'PaperMod'
timeZone = 'Asia/Shanghai'
buildFuture = true

# 分页设置
[pagination]
  pagerSize = 5

[params]
  # 主题模式
  defaultTheme = "auto" # auto, light, dark
  disableThemeToggle = false
  
  # 首页设置
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  
  # 搜索功能
  fuseOpts.isCaseSensitive = false
  fuseOpts.shouldSort = true
  fuseOpts.location = 0
  fuseOpts.distance = 1000
  fuseOpts.threshold = 0.4
  fuseOpts.minMatchCharLength = 0
  fuseOpts.keys = ["title", "permalink", "summary", "content"]

# 菜单配置
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 40
